/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Table: typeof import('./src/components/table/Table.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
